Repository ASFHyP3/gis-services, pull requests merged in 2023-05, with the labels that each got.

#80 Release v0.3.4
  CHANGELOG.md
  image_services/rtc_services/hkh/hkh_pw.json
  image_services/rtc_services/hkh/hkh_rgb.json
  image_services/rtc_services/hkh/hkh_rtc_vh.json
  image_services/rtc_services/hkh/hkh_rtc_vv.json
  image_services/rtc_services/hkh/hkh_wm.json
  image_services/rtc_services/nasa_disasters/rgb.json
  image_services/rtc_services/nasa_disasters/rtc_vh.json
  image_services/rtc_services/nasa_disasters/rtc_vv.json
  image_services/rtc_services/nasa_disasters/wm.json
  image_services/rtc_services/usda/usda_rgb.json
  image_services/rtc_services/usda/usda_rtc_vh.json
  image_services/rtc_services/usda/usda_rtc_vv.json
  image_services/rtc_services/usda/usda_wm.json
  image_services/rtc_services/usda/usda_wm_validzero_nd.json
Labels: patch

#51 Document workflow for publishing existing MDs to EGIS Image Server
  CHANGELOG.md
  image_services/egis/images/EditMetadata.PNG
  image_services/egis/images/PixelCachePath.PNG
  image_services/egis/images/RepairPaths.PNG
  image_services/egis/images/ShareAsWebLayer.PNG
  image_services/egis/images/ShareAsWebLayerDialog.PNG
  image_services/egis/images/UniqueNumericIDs.PNG
  image_services/egis/images/WMS.PNG
  image_services/egis/images/add-item-to-portal.png
  image_services/egis/images/arcgis-assistant.png
  image_services/egis/images/change-url.PNG
  image_services/egis/images/edit-json.PNG
  image_services/egis/images/new-item-url.png
  image_services/egis/images/view-item-json.PNG
  image_services/egis/publishing_MDCS_to_EGIS.md
  image_services/egis/sample_metadata_AMP.txt
  image_services/egis/sample_metadata_COH12.txt
  image_services/egis/sharing_content.md
  image_services/egis/updating_webmaps.md
Labels: documentation, patch

#82 Release v0.3.5 - EGIS Documentation
  CHANGELOG.md
  image_services/egis/images/EditMetadata.PNG
  image_services/egis/images/PixelCachePath.PNG
  image_services/egis/images/RepairPaths.PNG
  image_services/egis/images/ShareAsWebLayer.PNG
  image_services/egis/images/ShareAsWebLayerDialog.PNG
  image_services/egis/images/UniqueNumericIDs.PNG
  image_services/egis/images/WMS.PNG
  image_services/egis/images/add-item-to-portal.png
  image_services/egis/images/arcgis-assistant.png
  image_services/egis/images/change-url.PNG
  image_services/egis/images/edit-json.PNG
  image_services/egis/images/new-item-url.png
  image_services/egis/images/view-item-json.PNG
  image_services/egis/publishing_MDCS_to_EGIS.md
  image_services/egis/sample_metadata_AMP.txt
  image_services/egis/sample_metadata_COH12.txt
  image_services/egis/sharing_content.md
  image_services/egis/updating_webmaps.md
Labels: documentation, patch

#83 Enable pixel cache for image services
  CHANGELOG.md
  image_services/rtc_services/make_rtc_service.py
Labels: patch

#84 Set pixel cache path
  image_services/rtc_services/make_rtc_service.py
Labels: bumpless

#85 Remove pixel cache references
  CHANGELOG.md
  image_services/rtc_services/make_rtc_service.py
Labels: bumpless

#87 Update server url in server_setup.md
  image_server/server_setup.md
Labels: bumpless

#89 include hyp3-examples persmission in cf file
  image_server/cloudformation.yml
Labels: bumpless

#88 update the UNDM4 patch url
  image_server/arcgis_setup.sh
Labels: bumpless
