Repository ASFHyP3/gis-services, pull requests merged in 2023-06, with the labels that each got.

#91 Release v0.3.6
  CHANGELOG.md
  image_server/arcgis_setup.sh
  image_server/cloudformation.yml
  image_server/server_setup.md
Labels: patch

#92 Add code for generating ASF_SampleData services
  CHANGELOG.md
  image_services/sample_data/make_sample_service.py
  image_services/sample_data/raster_function_templates/Stretch_2SD_with_DRA.rft.xml
  image_services/sample_data/ridgecrest_amplitude.json
  image_services/sample_data/ridgecrest_coherence_12day.json
  image_services/sample_data/ridgecrest_los_12day.json
  image_services/sample_data/ridgecrest_unwrapped_12day.json
  image_services/sample_data/ridgecrest_vertical_12day.json
  image_services/sample_data/ridgecrest_wrapped_12day.json
  image_services/sample_data/rtc_10m.json
  image_services/sample_data/rtc_30m.json
  image_services/sample_data/rtc_amplitude_scale.json
  image_services/sample_data/rtc_db_scale.json
  image_services/sample_data/rtc_optional_area.json
  image_services/sample_data/rtc_optional_dem.json
  image_services/sample_data/rtc_optional_inc.json
  image_services/sample_data/rtc_optional_ls.json
  image_services/sample_data/rtc_optional_rgb.json
  image_services/sample_data/rtc_optional_rtc_vh.json
  image_services/sample_data/rtc_optional_rtc_vv.json
  image_services/sample_data/rtc_power_scale.json
  image_services/sample_data/rtc_speckle_no.json
  image_services/sample_data/rtc_speckle_yes.json
Labels: minor

#93 Add 16-bit unsigned integer type to sample data script
  image_services/sample_data/make_sample_service.py
Labels: bumpless

#94 Calculate statistics for sample data services
  image_services/sample_data/make_sample_service.py
Labels: bumpless

#95 Change hardcoded skip factor value to a variable
  image_services/sample_data/make_sample_service.py
Labels: bumpless

#97 resolve minor discrepancies in sample data configs
  image_services/sample_data/rtc_10m.json
  image_services/sample_data/rtc_30m.json
  image_services/sample_data/rtc_amplitude_scale.json
  image_services/sample_data/rtc_db_scale.json
  image_services/sample_data/rtc_optional_rtc_vh.json
  image_services/sample_data/rtc_optional_rtc_vv.json
  image_services/sample_data/rtc_power_scale.json
  image_services/sample_data/rtc_speckle_no.json
  image_services/sample_data/rtc_speckle_yes.json
Labels: bumpless

#96 Release v0.4.0 - Reusable script for Sample Data services
  CHANGELOG.md
  image_services/sample_data/make_sample_service.py
  image_services/sample_data/raster_function_templates/Stretch_2SD_with_DRA.rft.xml
  image_services/sample_data/ridgecrest_amplitude.json
  image_services/sample_data/ridgecrest_coherence_12day.json
  image_services/sample_data/ridgecrest_los_12day.json
  image_services/sample_data/ridgecrest_unwrapped_12day.json
  image_services/sample_data/ridgecrest_vertical_12day.json
  image_services/sample_data/ridgecrest_wrapped_12day.json
  image_services/sample_data/rtc_10m.json
  image_services/sample_data/rtc_30m.json
  image_services/sample_data/rtc_amplitude_scale.json
  image_services/sample_data/rtc_db_scale.json
  image_services/sample_data/rtc_optional_area.json
  image_services/sample_data/rtc_optional_dem.json
  image_services/sample_data/rtc_optional_inc.json
  image_services/sample_data/rtc_optional_ls.json
  image_services/sample_data/rtc_optional_rgb.json
  image_services/sample_data/rtc_optional_rtc_vh.json
  image_services/sample_data/rtc_optional_rtc_vv.json
  image_services/sample_data/rtc_power_scale.json
  image_services/sample_data/rtc_speckle_no.json
  image_services/sample_data/rtc_speckle_yes.json
Labels: minor

#99 Updated timeout parameters
  image_services/rtc_services/nasa_disasters/rgb.json
  image_services/rtc_services/nasa_disasters/rtc_vh.json
  image_services/rtc_services/nasa_disasters/rtc_vv.json
  image_services/rtc_services/nasa_disasters/wm.json
Labels: bumpless

#100 Release v0.4.1
  CHANGELOG.md
  image_services/rtc_services/nasa_disasters/rgb.json
  image_services/rtc_services/nasa_disasters/rtc_vh.json
  image_services/rtc_services/nasa_disasters/rtc_vv.json
  image_services/rtc_services/nasa_disasters/wm.json
Labels: patch

#86 Add image services for PDC
  CHANGELOG.md
  image_services/rtc_services/make_pdc_service.py
  image_services/rtc_services/pdc/pdc_rgb.json
  image_services/rtc_services/pdc/pdc_rtc_vh.json
  image_services/rtc_services/pdc/pdc_rtc_vv.json
  image_services/rtc_services/pdc/pdc_wm.json
Labels: patch

#98 Add in permissions for pdc bucket
  CHANGELOG.md
  image_server/cloudformation.yml
Labels: bumpless

#103 Refactor the addRasters retry loop
  CHANGELOG.md
  image_services/rtc_services/make_pdc_service.py
  image_services/rtc_services/make_rtc_service.py
Labels: patch

#104 Add in the sh script for pdc services
  image_services/rtc_services/make_pdc_service.sh
Labels: bumpless
