Repository ASFHyP3/gis-services, pull requests merged in 2023-04, with the labels that each got.

#65 switch make_rtc_service.sh from miniconda3 to mambaforge
  CHANGELOG.md
  image_services/rtc_services/make_rtc_service.sh
Labels: bumpless

#66 Change pixel type number for Float32 datasets
  image_services/rtc_services/make_rtc_service.py
Labels: bumpless

#67 Release v0.3.0
  CHANGELOG.md
  image_server/environment.yml
  image_services/rtc_services/hkh/hkh_rgb.json
  image_services/rtc_services/hkh/hkh_rtc_vh.json
  image_services/rtc_services/hkh/hkh_rtc_vv.json
  image_services/rtc_services/hkh/hkh_wm.json
  image_services/rtc_services/make_rtc_service.py
  image_services/rtc_services/make_rtc_service.sh
  image_services/rtc_services/nasa_disasters/rgb.json
  image_services/rtc_services/nasa_disasters/rtc_vh.json
  image_services/rtc_services/nasa_disasters/rtc_vv.json
  image_services/rtc_services/nasa_disasters/wm.json
  image_services/rtc_services/usda/usda_rgb.json
  image_services/rtc_services/usda/usda_rtc_vh.json
  image_services/rtc_services/usda/usda_rtc_vv.json
  image_services/rtc_services/usda/usda_wm.json
  image_services/rtc_services/usda/usda_wm_validzero_nd.json
Labels: minor

#69 Release v0.3.1
  CHANGELOG.md
  image_server/environment.yml
  image_services/rtc_services/make_rtc_service.py
Labels: patch

#60 Update server setup and config documentation
  CHANGELOG.md
  image_server/images/asf_services_user.png
  image_server/images/publisher_role.png
  image_server/server_setup.md
Labels: documentation

#70 Final edits to image server setup documentation
  image_server/server_setup.md
Labels: bumpless, documentation

#71 Release 0.3.2 - Image Server setup documentation
  CHANGELOG.md
  image_server/images/asf_services_user.png
  image_server/images/publisher_role.png
  image_server/server_setup.md
Labels: patch

#75 Fix num instances
  image_services/rtc_services/hkh/hkh_rgb.json
  image_services/rtc_services/hkh/hkh_rtc_vh.json
  image_services/rtc_services/hkh/hkh_rtc_vv.json
  image_services/rtc_services/hkh/hkh_wm.json
  image_services/rtc_services/nasa_disasters/rgb.json
  image_services/rtc_services/nasa_disasters/rtc_vh.json
  image_services/rtc_services/nasa_disasters/rtc_vv.json
  image_services/rtc_services/nasa_disasters/wm.json
  image_services/rtc_services/usda/usda_rgb.json
  image_services/rtc_services/usda/usda_rtc_vh.json
  image_services/rtc_services/usda/usda_rtc_vv.json
  image_services/rtc_services/usda/usda_wm.json
  image_services/rtc_services/usda/usda_wm_validzero_nd.json
Labels: bumpless

#77 Release v0.3.3
  CHANGELOG.md
  image_services/glo_30_hand/README.md
  image_services/rtc_services/hkh/hkh_rgb.json
  image_services/rtc_services/hkh/hkh_rtc_vh.json
  image_services/rtc_services/hkh/hkh_rtc_vv.json
  image_services/rtc_services/hkh/hkh_wm.json
  image_services/rtc_services/nasa_disasters/rgb.json
  image_services/rtc_services/nasa_disasters/rtc_vh.json
  image_services/rtc_services/nasa_disasters/rtc_vv.json
  image_services/rtc_services/nasa_disasters/wm.json
  image_services/rtc_services/usda/usda_rgb.json
  image_services/rtc_services/usda/usda_rtc_vh.json
  image_services/rtc_services/usda/usda_rtc_vv.json
  image_services/rtc_services/usda/usda_wm.json
  image_services/rtc_services/usda/usda_wm_validzero_nd.json
Labels: patch
