Repository ASFHyP3/gis-services, pull requests merged in 2023-03, with the labels that each got.

#36 Add lines in the config files to populate the metadata for the main REST Endpoint page
  image_services/rtc_services/rgb/rgb.json
  image_services/rtc_services/rtc/rtc_vh.json
  image_services/rtc_services/rtc/rtc_vv.json
  image_services/rtc_services/wm/wm.json
Labels: bumpless

#38 Release v0.1.0
  .github/CODEOWNERS
  .github/workflows/changelog.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .trufflehog.txt
  CHANGELOG.md
  image_server/arcgis_setup.sh
  image_server/cloudformation.yml
  image_server/environment.yml
  image_server/images/load_balancer.png
  image_server/images/new_role.png
  image_server/images/new_user.png
  image_server/images/raster_store.png
  image_server/images/stack_details.png
  image_server/root_setup.sh
  image_server/server_setup.md
  image_services/glo_30_hand/GLO30_HAND_2SDstretch.rft.xml
  image_services/glo_30_hand/make_hand_service.py
  image_services/rtc_services/make_rtc_service.py
  image_services/rtc_services/make_rtc_service.sh
  image_services/rtc_services/rgb/rgb.json
  image_services/rtc_services/rtc/Sentinel1_RTC_Amplitude.rft.xml
  image_services/rtc_services/rtc/Sentinel1_RTC_Power.rft.xml
  image_services/rtc_services/rtc/Sentinel1_RTC_dB.rft.xml
  image_services/rtc_services/rtc/Sentinel1_RTC_dB_Stretch.rft.xml
  image_services/rtc_services/rtc/rtc_vh.json
  image_services/rtc_services/rtc/rtc_vv.json
  image_services/rtc_services/wm/WatermapExtentBlueOnly.rft.xml
  image_services/rtc_services/wm/WatermapExtentWhiteandBlue.rft.xml
  image_services/rtc_services/wm/wm.json
Labels: minor

#41 change default water map raster template to WatermapExtentBlueOnly
  image_services/rtc_services/wm/wm.json
Labels: bumpless

#37 add github action for release checklist
  .github/workflows/release-checklist-comment.yml
Labels: bumpless

#43 Release v0.1.1
  .github/workflows/release-checklist-comment.yml
  CHANGELOG.md
  image_services/rtc_services/wm/wm.json
Labels: patch

#45 add in cleanup script for rtc services
  image_services/rtc_services/rtc_service_cleanup.sh
Labels: bumpless

#48 add in chmod
  image_services/rtc_services/rtc_service_cleanup.sh
Labels: bumpless

#50 Release v 0.1.2
  CHANGELOG.md
  image_services/rtc_services/rtc_service_cleanup.sh
Labels: patch

#57 Edit Service Configuration files
  image_services/rtc_services/hkh/hkh_rgb.json
  image_services/rtc_services/hkh/hkh_rtc_vh.json
  image_services/rtc_services/hkh/hkh_rtc_vv.json
  image_services/rtc_services/hkh/hkh_wm.json
  image_services/rtc_services/nasa_disasters/wm.json
  image_services/rtc_services/usda/usda_rgb.json
  image_services/rtc_services/usda/usda_rtc_vh.json
  image_services/rtc_services/usda/usda_rtc_vv.json
  image_services/rtc_services/usda/usda_wm.json
  image_services/rtc_services/usda/usda_wm_validzero_nd.json
Labels: bumpless

#58 add disclaimer to old format watermap service description
  image_services/rtc_services/usda/usda_wm.json
Labels: bumpless, documentation
