Repository ASFHyP3/gis-services, pull requests merged in 2023-08, with the labels that each got.

#119 Augment GroupName field content for Mosaic Overview
  image_services/egis/make_egis_services.py
Labels: patch

#121 Set a custom Tag field value for overview record
  image_services/egis/make_egis_services.py
Labels: bumpless

#120 Add GSSICB COH06 config and service metadata files
  CHANGELOG.md
  image_services/egis/config/COH06_HH_DJF.json
  image_services/egis/config/COH06_HH_JJA.json
  image_services/egis/config/COH06_HH_MAM.json
  image_services/egis/config/COH06_HH_SON.json
  image_services/egis/config/COH06_VV_DJF.json
  image_services/egis/config/COH06_VV_JJA.json
  image_services/egis/config/COH06_VV_MAM.json
  image_services/egis/config/COH06_VV_SON.json
  image_services/egis/metadata/print_service_metadata.py
  image_services/egis/metadata/service_metadata/COH06_HH_DJF_metadata.txt
  image_services/egis/metadata/service_metadata/COH06_HH_JJA_metadata.txt
  image_services/egis/metadata/service_metadata/COH06_HH_MAM_metadata.txt
  image_services/egis/metadata/service_metadata/COH06_HH_SON_metadata.txt
  image_services/egis/metadata/service_metadata/COH06_VV_DJF_metadata.txt
  image_services/egis/metadata/service_metadata/COH06_VV_JJA_metadata.txt
  image_services/egis/metadata/service_metadata/COH06_VV_MAM_metadata.txt
  image_services/egis/metadata/service_metadata/COH06_VV_SON_metadata.txt
  image_services/egis/metadata/templates/coherence.txt.j2
Labels: bumpless

#122 Release 0.6.0 - GSSICB Scripts
  .github/workflows/create-jira-issue.yml
  CHANGELOG.md
  image_server/cloudformation.yml
  image_services/egis/config/COH06_HH_DJF.json
  image_services/egis/config/COH06_HH_JJA.json
  image_services/egis/config/COH06_HH_MAM.json
  image_services/egis/config/COH06_HH_SON.json
  image_services/egis/config/COH06_VV_DJF.json
  image_services/egis/config/COH06_VV_JJA.json
  image_services/egis/config/COH06_VV_MAM.json
  image_services/egis/config/COH06_VV_SON.json
  image_services/egis/make_egis_services.py
  image_services/egis/metadata/print_service_metadata.py
  image_services/egis/metadata/service_metadata/COH06_HH_DJF_metadata.txt
  image_services/egis/metadata/service_metadata/COH06_HH_JJA_metadata.txt
  image_services/egis/metadata/service_metadata/COH06_HH_MAM_metadata.txt
  image_services/egis/metadata/service_metadata/COH06_HH_SON_metadata.txt
  image_services/egis/metadata/service_metadata/COH06_VV_DJF_metadata.txt
  image_services/egis/metadata/service_metadata/COH06_VV_JJA_metadata.txt
  image_services/egis/metadata/service_metadata/COH06_VV_MAM_metadata.txt
  image_services/egis/metadata/service_metadata/COH06_VV_SON_metadata.txt
  image_services/egis/metadata/templates/coherence.txt.j2
  image_services/egis/raster_function_templates/ScaledCoherence.rft.xml
  image_services/egis/raster_function_templates/UnscaledCoherence.rft.xml
Labels: minor

#124 Documentation for new GSSICB script
  image_services/egis/images/ShareAsWebLayerDialogMetadata.PNG
  image_services/egis/publishing_GSSICB_to_EGIS.md
Labels: bumpless, documentation

#127 Documentation for publishing web maps in EGIS
  CHANGELOG.md
  image_services/egis/docs/images/EditMetadata.PNG
  image_services/egis/docs/images/PixelCachePath.PNG
  image_services/egis/docs/images/RepairPaths.PNG
  image_services/egis/docs/images/ShareAsWebLayer.PNG
  image_services/egis/docs/images/ShareAsWebLayerDialog.PNG
  image_services/egis/docs/images/ShareAsWebLayerDialogMetadata.PNG
  image_services/egis/docs/images/UniqueNumericIDs.PNG
  image_services/egis/docs/images/WMS.PNG
  image_services/egis/docs/images/add-item-to-portal.png
  image_services/egis/docs/images/arcgis-assistant.png
  image_services/egis/docs/images/change-url.PNG
  image_services/egis/docs/images/edit-json.PNG
  image_services/egis/docs/images/egis-add-content.png
  image_services/egis/docs/images/egis-add-group.png
  image_services/egis/docs/images/egis-add-url-layer.PNG
  image_services/egis/docs/images/egis-add-url.png
  image_services/egis/docs/images/egis-copy-popup.png
  image_services/egis/docs/images/egis-deselect-fields.PNG
  image_services/egis/docs/images/egis-group-contents.PNG
  image_services/egis/docs/images/egis-item-desc-url.png
  image_services/egis/docs/images/egis-map-tab.png
  image_services/egis/docs/images/egis-map-viewer.png
  image_services/egis/docs/images/egis-move-text.png
  image_services/egis/docs/images/egis-paste-source.png
  image_services/egis/docs/images/egis-popup-check-bad.png
  image_services/egis/docs/images/egis-popup-check.png
  image_services/egis/docs/images/egis-popups.png
  image_services/egis/docs/images/egis-rename-group.png
  image_services/egis/docs/images/egis-save-details.PNG
  image_services/egis/docs/images/egis-save-map.PNG
  image_services/egis/docs/images/egis-share-dialog.PNG
  image_services/egis/docs/images/egis-share-map.png
  image_services/egis/docs/images/egis-significant-digits.png
  image_services/egis/docs/images/egis-source.png
  image_services/egis/docs/images/new-item-url.png
  image_services/egis/docs/images/view-item-json.PNG
  image_services/egis/docs/publishing_GSSICB_to_EGIS.md
  image_services/egis/docs/publishing_GSSICB_webmap.md
  image_services/egis/docs/publishing_MDCS_to_EGIS.md
  image_services/egis/docs/sharing_content.md
  image_services/egis/docs/updating_webmaps.md
  image_services/egis/metadata/sample_metadata_AMP.txt
  image_services/egis/metadata/sample_metadata_COH12.txt
Labels: documentation

#128 Add documentation for populating the Item Description for a webmap
  image_services/egis/docs/images/egis-credits.png
  image_services/egis/docs/images/egis-edit-item-description.png
  image_services/egis/docs/images/egis-map-description.PNG
  image_services/egis/docs/publishing_GSSICB_webmap.md
Labels: bumpless, documentation

#129 Release 0.6.1 - Documentation for publishing EGIS Web Maps
  CHANGELOG.md
  image_services/egis/docs/images/EditMetadata.PNG
  image_services/egis/docs/images/PixelCachePath.PNG
  image_services/egis/docs/images/RepairPaths.PNG
  image_services/egis/docs/images/ShareAsWebLayer.PNG
  image_services/egis/docs/images/ShareAsWebLayerDialog.PNG
  image_services/egis/docs/images/ShareAsWebLayerDialogMetadata.PNG
  image_services/egis/docs/images/UniqueNumericIDs.PNG
  image_services/egis/docs/images/WMS.PNG
  image_services/egis/docs/images/add-item-to-portal.png
  image_services/egis/docs/images/arcgis-assistant.png
  image_services/egis/docs/images/change-url.PNG
  image_services/egis/docs/images/edit-json.PNG
  image_services/egis/docs/images/egis-add-content.png
  image_services/egis/docs/images/egis-add-group.png
  image_services/egis/docs/images/egis-add-url-layer.PNG
  image_services/egis/docs/images/egis-add-url.png
  image_services/egis/docs/images/egis-copy-popup.png
  image_services/egis/docs/images/egis-credits.png
  image_services/egis/docs/images/egis-deselect-fields.PNG
  image_services/egis/docs/images/egis-edit-item-description.png
  image_services/egis/docs/images/egis-group-contents.PNG
  image_services/egis/docs/images/egis-item-desc-url.png
  image_services/egis/docs/images/egis-map-description.PNG
  image_services/egis/docs/images/egis-map-tab.png
  image_services/egis/docs/images/egis-map-viewer.png
  image_services/egis/docs/images/egis-move-text.png
  image_services/egis/docs/images/egis-paste-source.png
  image_services/egis/docs/images/egis-popup-check-bad.png
  image_services/egis/docs/images/egis-popup-check.png
  image_services/egis/docs/images/egis-popups.png
  image_services/egis/docs/images/egis-rename-group.png
  image_services/egis/docs/images/egis-save-details.PNG
  image_services/egis/docs/images/egis-save-map.PNG
  image_services/egis/docs/images/egis-share-dialog.PNG
  image_services/egis/docs/images/egis-share-map.png
  image_services/egis/docs/images/egis-significant-digits.png
  image_services/egis/docs/images/egis-source.png
  image_services/egis/docs/images/new-item-url.png
  image_services/egis/docs/images/view-item-json.PNG
  image_services/egis/docs/publishing_GSSICB_to_EGIS.md
  image_services/egis/docs/publishing_GSSICB_webmap.md
  image_services/egis/docs/publishing_MDCS_to_EGIS.md
  image_services/egis/docs/sharing_content.md
  image_services/egis/docs/updating_webmaps.md
  image_services/egis/metadata/sample_metadata_AMP.txt
  image_services/egis/metadata/sample_metadata_COH12.txt
Labels: patch

#133 Release v0.6.2
  CHANGELOG.md
  image_server/arcgis_setup.sh
  image_server/cloudformation.yml
Labels: patch
