Repository ASFHyP3/gis-services, pull requests merged in 2023-07, with the labels that each got.

#81 Enable WMS in image services
  CHANGELOG.md
  image_services/rtc_services/make_pdc_service.py
  image_services/rtc_services/make_rtc_service.py
  image_services/rtc_services/nasa_disasters/rgb.json
  image_services/rtc_services/nasa_disasters/rtc_vh.json
  image_services/rtc_services/nasa_disasters/rtc_vv.json
  image_services/rtc_services/nasa_disasters/wm.json
  image_services/rtc_services/pdc/pdc_rgb.json
  image_services/rtc_services/pdc/pdc_rtc_vh.json
  image_services/rtc_services/pdc/pdc_rtc_vv.json
  image_services/rtc_services/pdc/pdc_wm.json
  image_services/rtc_services/usda/usda_rgb.json
  image_services/rtc_services/usda/usda_rtc_vh.json
  image_services/rtc_services/usda/usda_rtc_vv.json
  image_services/rtc_services/usda/usda_wm.json
  image_services/rtc_services/usda/usda_wm_validzero_nd.json
Labels: minor

#110 Correct service titles for HKH and PDC
  image_services/rtc_services/hkh/hkh_rgb.json
  image_services/rtc_services/hkh/hkh_rtc_vh.json
  image_services/rtc_services/hkh/hkh_rtc_vv.json
  image_services/rtc_services/hkh/hkh_wm.json
  image_services/rtc_services/pdc/pdc_rgb.json
  image_services/rtc_services/pdc/pdc_rtc_vh.json
  image_services/rtc_services/pdc/pdc_rtc_vv.json
  image_services/rtc_services/pdc/pdc_wm.json
Labels: bumpless

#111 Release v0.5.1
  CHANGELOG.md
  image_services/rtc_services/hkh/hkh_pw.json
  image_services/rtc_services/hkh/hkh_rgb.json
  image_services/rtc_services/hkh/hkh_rtc_vh.json
  image_services/rtc_services/hkh/hkh_rtc_vv.json
  image_services/rtc_services/hkh/hkh_wm.json
  image_services/rtc_services/make_rtc_service.py
  image_services/rtc_services/pdc/pdc_rgb.json
  image_services/rtc_services/pdc/pdc_rtc_vh.json
  image_services/rtc_services/pdc/pdc_rtc_vv.json
  image_services/rtc_services/pdc/pdc_wm.json
  image_services/sample_data/make_sample_service.py
Labels: patch

#113 Add `create-jira-issue` workflow
  .github/workflows/create-jira-issue.yml
Labels: bumpless
