Repository ASFHyP3/gis-services, pull requests merged in 2024-01, with the labels that each got.

#158 Release v0.6.7
  CHANGELOG.md
  image_services/opera/config/rtc_hh_test.json
  image_services/opera/config/rtc_vv.json
  image_services/opera/config/rtc_vv_urls.json
  image_services/opera/make_opera_md.py
  image_services/opera/make_opera_services_test.py
  image_services/opera/update_opera_urls.py
Labels: patch

#146 Update documentation for publishing services to EGIS
  CHANGELOG.md
  image_services/egis/docs/publishing_GSSICB_to_EGIS.md
Labels: documentation

#163 Clean up CF file
  image_server/cloudformation.yml
Labels: bumpless
